### ISSUE TITLE
Updater crashes

### ISSUE THREAD

**Issue by kingofhell213** [shishkabob27/CardWars#21]
When I launch the updated it crashes when generating Local Manifest

the log says this:

Unhandled exception in script
Failed to execute script 'main' due to unhandled exception:[Errno 13] permission denied

Traceback (most recent call last):
  File "main.py", line 210, in <module>
  File "main.py", line 131, in check_for_updates
  File "main.py", line 38, in generate_manifest
PermissionError: [Errno 13] Permission denied

**Comment by kingofhell213** [comment]
The game also doesn't launch. If I try to launch the game itself by clicking it's .exe rather than the updates, it'll show up in task manager but the game itself doesn't appear at all.
